import type { Metadata } from "next";
import "./globals.css";
import "./mobile.css";
import "./footer.css";
import "./header.css";

import { Header } from "@/components/layout/bcbsms-header";
import { Footer } from "@/components/layout/bcbsms-footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Header />
        <main className="mx-auto w-[1200px] max-w-full px-4">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
